export const GET_GAME_KEY = 'GET_GAME_KEY'
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const PLAYER_INFO = 'PLAYER_INFO'
export const USER_AVATAR = 'USER_AVATAR'
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE'


